-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdlcoder_I2C_ssm2603\I2C_SSM2603_src_I2C_SSM2603_pkg.vhd
-- Created: 2020-11-19 16:06:43
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE I2C_SSM2603_src_I2C_SSM2603_pkg IS
  TYPE T_state_type_is_i2c_cfg IS (IN_end_state, IN_finish1, IN_init, IN_load_last_reg, IN_load_lut_data, IN_lut_incr1, IN_wait_state1);
  TYPE T_state_type_is_i2c_mstr IS (IN_Increment_Byte_count, IN_Increment_Byte_count1, IN_ack_addr_m, IN_ack_addr_m_cnf, IN_ack_addrm1, IN_ack_data, IN_ack_data_cnf, IN_ack_slv, IN_ack_slv_cnf, IN_cmd_reg_addr_n, IN_cmd_reg_addr_p, IN_cmd_reg_data_n, IN_cmd_reg_data_p, IN_cmd_slave_addr_n, IN_cmd_slave_addr_p, IN_idle, IN_nack_addrm, IN_nack_addrm1, IN_nack_addrm_cnf, IN_nack_data, IN_nack_data_cnf, IN_nack_slv, IN_nack_slv_cnf, IN_ready, IN_scl_ext_n, IN_scl_ext_p, IN_start_n, IN_start_p, IN_stop, IN_stop_ext, IN_write_n, IN_write_p);
END I2C_SSM2603_src_I2C_SSM2603_pkg;

