-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hdlcoder_I2C_ssm2603\I2C_SSM2603_dut.vhd
-- Created: 2020-11-19 16:10:08
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: I2C_SSM2603_dut
-- Source Path: I2C_SSM2603/I2C_SSM2603_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY I2C_SSM2603_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        I2C_CLK                           :   OUT   std_logic;  -- ufix1
        I2C_DATA                          :   INOUT std_logic;  -- ufix1
        MUTEN                             :   OUT   std_logic;  -- ufix1
        Dammy                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END I2C_SSM2603_dut;


ARCHITECTURE rtl OF I2C_SSM2603_dut IS

  -- Component Declarations
  COMPONENT I2C_SSM2603_src_I2C_SSM2603
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          ce_out                          :   OUT   std_logic;  -- ufix1
          I2C_CLK                         :   OUT   std_logic;  -- ufix1
          I2C_DATA                        :   INOUT std_logic;  -- ufix1
          MUTEN                           :   OUT   std_logic;  -- ufix1
          Dammy                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : I2C_SSM2603_src_I2C_SSM2603
    USE ENTITY work.I2C_SSM2603_src_I2C_SSM2603(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL I2C_CLK_sig                      : std_logic;  -- ufix1
  SIGNAL MUTEN_sig                        : std_logic;  -- ufix1
  SIGNAL Dammy_sig                        : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_I2C_SSM2603_src_I2C_SSM2603 : I2C_SSM2603_src_I2C_SSM2603
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              ce_out => ce_out_sig,  -- ufix1
              I2C_CLK => I2C_CLK_sig,  -- ufix1
              I2C_DATA => I2C_DATA,  -- ufix1
              MUTEN => MUTEN_sig,  -- ufix1
              Dammy => Dammy_sig  -- ufix8
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  I2C_CLK <= I2C_CLK_sig;

  MUTEN <= MUTEN_sig;

  Dammy <= Dammy_sig;

END rtl;

