function hRD = plugin_rd()
% Reference design definition

%   Copyright 2012-2020 The MathWorks, Inc.

% Construct reference design object
hRD = hdlcoder.ReferenceDesign('SynthesisTool', 'Altera QUARTUS II');

hRD.ReferenceDesignName = 'Audio System';
hRD.BoardName = 'Arrow SoCKit for Audio';

% Tool information
hRD.SupportedToolVersion = {'16.0'};

%% Add custom design files
% add custom Qsys design
hRD.addCustomQsysDesign( ...
    'CustomQsysPrjFile', 'audioSystemSockit.qsys');
% Add constraint files
hRD.CustomConstraints = {'audioSystemSockit.tcl'};
hRD.addIPRepository(...
    'IPListFunction', 'myArrowSoCKit.hdlcoder_audio_iplist',...
    'NotExistMessage', 'IP repository not found');

%% Add interfaces
% add clock interface
hRD.addClockInterface( ...
    'ClockConnection',     'pll_0.outclk0', ...
    'ResetConnection',     'hps_0.h2f_reset',...
    'DefaultFrequencyMHz', 50,...
    'MinFrequencyMHz',     5,...
    'MaxFrequencyMHz',     500,...
    'ClockModuleInstance', 'pll_0',...
    'ClockNumber',         0); 

% add AXI4 slave interfaces
hRD.addAXI4SlaveInterface( ...
    'InterfaceConnection', 'hps_0.h2f_axi_master', ...
    'BaseAddress',         '0x0000');

hRD.addAXI4StreamInterface( ...
    'MasterChannelEnable',      true, ...
    'SlaveChannelEnable',       true, ...
    'MasterChannelConnection', 'I2S_SSM2603_0.AXI4_Stream_Slave', ...
    'SlaveChannelConnection',  'I2S_SSM2603_0.AXI4_Stream_Master', ...
    'MasterChannelDataWidth',   48, ...
    'SlaveChannelDataWidth',    48 ...
    );

hRD.DeviceTreeName = 'devicetree_axilite_iio.dtb';

% LocalWords:  AXI axi qsys CKit hps CKit Addr IPCORE Prj
           
