function hB = plugin_board()
% Board definition

%   Copyright 2014 The MathWorks, Inc.

% Construct board object
hB = hdlcoder.Board;

hB.BoardName    = 'Arrow SoCKit for Audio';

% FPGA device information
hB.FPGAVendor   = 'Altera';
hB.FPGAFamily   = 'Cyclone V';
hB.FPGADevice   = '5CSXFC6D6F31C6';
hB.FPGAPackage  = '';
hB.FPGASpeed    = '';

% Tool information
hB.SupportedTool = {'Altera QUARTUS II'};

% FPGA JTAG chain position
hB.JTAGChainPosition = 1;

%% Add interfaces
% Standard "External Port" interface
hB.addExternalPortInterface( ...
    'IOPadConstraint', {'IO_STANDARD "2.5V"'});

% Custom board external I/O interface
hB.addExternalIOInterface( ...
    'InterfaceID',    'LEDs General Purpose', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'GPLED', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'AF10', 'AD10', 'AE11', 'AD7'}, ...
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'});
    
hB.addExternalIOInterface( ...
    'InterfaceID',    'Push Buttons', ...
    'InterfaceType',  'IN', ...
    'PortName',       'GPKEY', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'AE9', 'AE12', 'AD9', 'AD11'}, ...
    'IOPadConstraint', {'IO_STANDARD "3.3-V LVTTL"'});

hB.addExternalIOInterface( ...
    'InterfaceID',    'Switches', ...
    'InterfaceType',  'IN', ...
    'PortName',       'GPSW', ...
    'PortWidth',      4, ...
    'FPGAPin',        {'W25', 'V25', 'AC28', 'AC29'}, ...
    'IOPadConstraint', {'IO_STANDARD "2.5V"'});

% LocalWords:  CKit CSXFC GPLED AE LVTTL GPKEY GPSW
